steps:
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        docker buildx create --use --name cbuilder || docker buildx use cbuilder

        docker buildx build \
          --platform linux/amd64 \
          --load \
          -t "${_IMAGE_URI}" \
          ./src/adservice

        docker push "${_IMAGE_URI}"

images:
  - "${_IMAGE_URI}"
