apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-monitor
  namespace: monitoring
  labels:
    release: my-monitoring
spec:
  # Allows Prometheus to find the service in 'default' while the monitor is in 'monitoring'
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: redis-cart
  endpoints:
  - port: redis-exporter
    interval: 15s