apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
spec:
  template:
    spec:
      containers:
      - name: server
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 150m
