apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice
spec:
  template:
    spec:
      containers:
      - name: server
        resources:
          requests:
            cpu: 50m
          limits:
            cpu: 100m
