apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: adservice
  namespace: default
spec:
  provider: istio
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: adservice

  progressDeadlineSeconds: 600

  service:
    port: 9555
    targetPort: 9555

  analysis:
    interval: 30s
    threshold: 2
    maxWeight: 50
    stepWeight: 25
    metrics:
      - name: request-success-rate
        thresholdRange:
          min: 99
        interval: 30s
      - name: request-duration
        thresholdRange:
          max: 800
        interval: 30s
